name: Manual Plugin Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g v1.0.0)"
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tar file of the plugin folder
        run: |
          tar -czvf plugins-${{ github.event.inputs.version }}.tar.gz plugins

      - name: Create GitHub release and upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create plugins-${{ github.event.inputs.version }} \
            plugins-${{ github.event.inputs.version }}.tar.gz \
            --title "Release plugins-${{ github.event.inputs.version }}" \
            --notes "Release of plugins version ${{ github.event.inputs.version }}"